### ISSUE TITLE
HLGLb not working?

### ISSUE THREAD

**Issue by quietvoid** [jpsdr/HDRTools#1]
Hi, thanks for this.
I am using release 0.3.
I'm having issues with black levels when going from BT.2020 PQ to BT.709 HLG, it's introducing banding in near blacks.
I tried adjusting HLGLb but it seems to make no difference.

The issue doesn't happen when doing YUV -> XYZ -> HDRtoSDR -> YUV.

The script:
>ConvertYUVtoXYZ(Color=1)
>ConvertXYZtoYUV(pColor=1)
>ConvertYUVtoLinearRGB(Color=0,OOTF=false)
>ConvertLinearRGBtoYUV(Color=0,HDRMode=1,HLGLw=1200,HLGColor=2,OOTF=false)

Images are in order: Untouched BT.2020 PQ and BT.709 HLG

![untouched](https://user-images.githubusercontent.com/39477805/43482053-a3818d80-94d5-11e8-93e3-30f4e7d479a7.png)
![hlg709](https://user-images.githubusercontent.com/39477805/43482054-a38ef092-94d5-11e8-852a-b0196fda3fef.png)

Thank you.

**Comment by jpsdr** [comment]
First, your script is wrong. The 2 first line convert BT.2020 SDR (or at least, NOT PQ) to BT.709 SDR. Your video is BT.2020 PQ, so, these 2 lines mess the video. To do what you want, you only need the last 2 lines of the script. What is the bitdepth of your input video ? First, try with only the last 2 lines.
Do you have a link to your video ? A sample with this scene ?

**Comment by quietvoid** [comment]
I realized afterwards that the gamut mapping had to be applied after.
The input is YUV420P16 but the source is 10 bit, the issue is still there with just PQ to HLG.

Sample where it happens.
[Sony Bravia OLED 4K Demo sample.zip](https://github.com/jpsdr/HDRTools/files/2251918/Sony.Bravia.OLED.4K.Demo.sample.zip)

Originally I only tried HLG conversion because it looked better than current scalar HDR to SDR for highlights, so the "issue" might be the intended result for HLG.

**Comment by jpsdr** [comment]
Maybe try ConvertYUVtoLinearRGB(Color=0,OOTF=false,OutputMode=2) for the 1rst line. Not at home now, don't know when i'll be able to test if it produce better result. If not, for now, i don't know what to do. Convert is pure math formula, if despite being 16 bits there is still precision loss...
BTW, for now, with the furmula i'm using, indeed HLGLb is not used. I've put the parameters in the plugin before realy begin to go deep in the code, and finaly for now HLGLb is not used, but HLGLw is ! I keep the parameter for now, in case in the future it happens to be used.

Ah... And as i said in the readme, don't expect great things from my HDR to SDR, as it's just a simple scaling factor i've made just to see out of curiosity what result it produces. If the solution was so simple, it would have been done since a long time ago.

**Comment by quietvoid** [comment]
OutputMode=2 seems to fix it!
Thank you !
I saw on doom9 that you planned on adding Hable and other algorithms for HDR to SDR, which is nice.
I had some success building HDRTools with Reinhard and Mobius (from https://github.com/ifb/vapoursynth-tonemap) applied to the XYZ 32 bit float function.
Reinhard worked well, but Mobius is shifting blue to purple and I can't figure out why, so I'm hoping you have more success than I did :)

Thank you again.
